version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: '2gb'
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444